ERROR 2024-06-21 18:49:40,664 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
ERROR 2024-06-21 18:49:40,673 basehttp "GET / HTTP/1.1" 500 145
ERROR 2024-06-21 18:52:58,830 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
ERROR 2024-06-21 18:52:58,839 basehttp "GET / HTTP/1.1" 500 145
ERROR 2024-06-21 18:57:17,024 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
ERROR 2024-06-21 18:57:17,034 basehttp "GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
"GET / HTTP/1.1" 500 145
ERROR 2024-06-22 09:14:38,646 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
ERROR 2024-06-22 09:14:38,651 basehttp "GET / HTTP/1.1" 500 145
ERROR 2024-06-22 09:16:14,998 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for '/blog/css/style.css'
ERROR 2024-06-22 09:16:15,000 basehttp "GET / HTTP/1.1" 500 145
ERROR 2024-06-22 10:20:27,549 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'blog/js/active.js'
ERROR 2024-06-22 10:20:27,553 basehttp "GET / HTTP/1.1" 500 145
ERROR 2024-06-22 13:59:26,451 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'send' not found. 'send' is not a valid view function or pattern name.
ERROR 2024-06-22 13:59:26,455 basehttp "GET / HTTP/1.1" 500 141504
ERROR 2024-06-22 14:04:49,916 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'inbox/send' not found. 'inbox/send' is not a valid view function or pattern name.
ERROR 2024-06-22 14:04:49,918 basehttp "GET / HTTP/1.1" 500 141648
ERROR 2024-06-22 14:05:17,456 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'send-item' not found. 'send-item' is not a valid view function or pattern name.
ERROR 2024-06-22 14:05:17,458 basehttp "GET / HTTP/1.1" 500 141639
ERROR 2024-06-22 14:20:03,860 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\users\signals.py", line 13, in save_profile
    instance.profile.save()
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\users\models.py", line 16, in save
    img = Image.open(self.image.path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\PIL\Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dubba\\OneDrive\\Desktop\\Fullstack\\Module5_Django\\media\\profile_pics\\ac6.jpg'
ERROR 2024-06-22 14:20:03,868 basehttp "POST /login/ HTTP/1.1" 500 173135
ERROR 2024-06-23 11:08:58,739 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\users\signals.py", line 13, in save_profile
    instance.profile.save()
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\users\models.py", line 16, in save
    img = Image.open(self.image.path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\PIL\Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dubba\\OneDrive\\Desktop\\Fullstack\\Module5_Django\\media\\profile_pics\\ac6.jpg'
ERROR 2024-06-23 11:08:58,748 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 190405
ERROR 2024-06-23 11:09:28,137 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\users\signals.py", line 13, in save_profile
    instance.profile.save()
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\users\models.py", line 16, in save
    img = Image.open(self.image.path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\PIL\Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dubba\\OneDrive\\Desktop\\Fullstack\\Module5_Django\\media\\profile_pics\\ac6.jpg'
ERROR 2024-06-23 11:09:28,142 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 190405
ERROR 2024-06-23 11:25:22,839 log Internal Server Error: /post/3/update/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 108, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 332, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (statuscontent) specified for Post
ERROR 2024-06-23 11:25:22,842 basehttp "GET /post/3/update/ HTTP/1.1" 500 120124
ERROR 2024-06-23 11:27:51,756 log Internal Server Error: /post/3/update/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 108, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 332, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (statuscontent) specified for Post
ERROR 2024-06-23 11:27:51,758 basehttp "GET /post/3/update/ HTTP/1.1" 500 120261
ERROR 2024-06-23 11:28:09,097 log Internal Server Error: /post/3/update/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 108, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 332, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (statuscontent) specified for Post
ERROR 2024-06-23 11:28:09,099 basehttp "GET /post/3/update/ HTTP/1.1" 500 120124
ERROR 2024-06-23 11:28:13,220 log Internal Server Error: /post/new/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 178, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 108, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 332, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (statuscontent) specified for Post
ERROR 2024-06-23 11:28:13,222 basehttp "GET /post/new/ HTTP/1.1" 500 116236
ERROR 2024-06-23 11:31:57,397 log Internal Server Error: /post/new/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 178, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 108, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 332, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (statuscontent) specified for Post
ERROR 2024-06-23 11:31:57,400 basehttp "GET /post/new/ HTTP/1.1" 500 116374
ERROR 2024-06-23 11:32:42,849 log Internal Server Error: /post/3/update/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 108, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\forms\models.py", line 332, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (statuscontent) specified for Post
ERROR 2024-06-23 11:32:42,852 basehttp "GET /post/3/update/ HTTP/1.1" 500 120124
ERROR 2024-06-23 11:40:50,447 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'blog/css/style.css'
ERROR 2024-06-23 11:40:50,449 basehttp "GET / HTTP/1.1" 500 145
ERROR 2024-06-23 12:09:50,709 log Internal Server Error: /inbox/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 10, in inbox
    return render(request, 'private_message/inbox.html', {'privatemessages': privatemessages})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'archive_message' not found. 'archive_message' is not a valid view function or pattern name.
ERROR 2024-06-23 12:09:50,714 basehttp "GET /inbox/ HTTP/1.1" 500 178258
ERROR 2024-06-23 12:28:31,568 log Internal Server Error: /inbox/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 10, in inbox
    return render(request, 'private_message/inbox.html', {'privatemessages': privatemessages})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'message_confirm_delete' not found. 'message_confirm_delete' is not a valid view function or pattern name.
ERROR 2024-06-23 12:28:31,572 basehttp "GET /inbox/ HTTP/1.1" 500 177607
ERROR 2024-06-23 12:45:58,930 log Internal Server Error: /inbox/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 10, in inbox
    return render(request, 'private_message/inbox.html', {'privatemessages': privatemessages})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'message_confirm_delete' not found. 'message_confirm_delete' is not a valid view function or pattern name.
ERROR 2024-06-23 12:45:58,935 basehttp "GET /inbox/ HTTP/1.1" 500 177594
ERROR 2024-06-23 12:46:35,092 log Internal Server Error: /inbox/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 10, in inbox
    return render(request, 'private_message/inbox.html', {'privatemessages': privatemessages})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'item_confirm_delete' not found. 'item_confirm_delete' is not a valid view function or pattern name.
ERROR 2024-06-23 12:46:35,095 basehttp "GET /inbox/ HTTP/1.1" 500 177659
ERROR 2024-06-23 12:51:43,538 log Internal Server Error: /inbox/confirm-delete/6/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 28, in item_confirm_delete
    return render(request, 'item_confirm_delete.html', {'privatemessage': privatemessage})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: item_confirm_delete.html
ERROR 2024-06-23 12:51:43,541 basehttp "GET /inbox/confirm-delete/6/ HTTP/1.1" 500 94337
ERROR 2024-06-23 12:52:37,870 log Internal Server Error: /inbox/archive/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: archive() missing 1 required positional argument: 'pk'
ERROR 2024-06-23 12:52:37,871 basehttp "GET /inbox/archive/ HTTP/1.1" 500 73005
ERROR 2024-06-23 12:56:23,586 log Internal Server Error: /inbox/archive/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 15, in archive
    return render(request, 'archive.html', {'privatemessages': privatemessages})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: archive.html
ERROR 2024-06-23 12:56:23,588 basehttp "GET /inbox/archive/ HTTP/1.1" 500 94364
ERROR 2024-06-23 12:58:49,393 log Internal Server Error: /inbox/archive/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 15, in archive
    return render(request, 'archive.html', {'privatemessages': privatemessages})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: archive.html
ERROR 2024-06-23 12:58:49,396 basehttp "GET /inbox/archive/ HTTP/1.1" 500 94364
ERROR 2024-06-23 13:08:17,719 log Internal Server Error: /inbox/confirm-delete/10/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 28, in item_confirm_delete
    return render(request, 'private_message/item_confirm_delete.html', {'privatemessage': privatemessage})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_message' with arguments '('',)' not found. 1 pattern(s) tried: ['inbox/delete\\-message/(?P<pk>[0-9]+)/\\Z']
ERROR 2024-06-23 13:08:17,723 basehttp "GET /inbox/confirm-delete/10/ HTTP/1.1" 500 165659
ERROR 2024-06-23 13:09:36,650 log Internal Server Error: /inbox/confirm-delete/10/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 28, in item_confirm_delete
    return render(request, 'private_message/item_confirm_delete.html', {'privatemessage': privatemessage})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_message' with no arguments not found. 1 pattern(s) tried: ['inbox/delete\\-message/(?P<pk>[0-9]+)/\\Z']
ERROR 2024-06-23 13:09:36,653 basehttp "GET /inbox/confirm-delete/10/ HTTP/1.1" 500 164091
ERROR 2024-06-23 13:12:06,957 log Internal Server Error: /inbox/confirm-delete/10/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 28, in item_confirm_delete
    return render(request, 'private_message/item_confirm_delete.html', {'privatemessage': privatemessage})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_item' not found. 'delete_item' is not a valid view function or pattern name.
ERROR 2024-06-23 13:12:06,961 basehttp "GET /inbox/confirm-delete/10/ HTTP/1.1" 500 162398
ERROR 2024-06-23 13:14:39,120 log Internal Server Error: /inbox/confirm-delete/10/
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\private_message\views.py", line 28, in item_confirm_delete
    return render(request, 'private_message/item_confirm_delete.html', {'privatemessage': privatemessage})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_message' with arguments '('',)' not found. 1 pattern(s) tried: ['inbox/delete\\-message/(?P<pk>[0-9]+)/\\Z']
ERROR 2024-06-23 13:14:39,123 basehttp "GET /inbox/confirm-delete/10/ HTTP/1.1" 500 165479
ERROR 2024-06-23 16:31:44,274 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\files\storage\handler.py", line 35, in __getitem__
    return self._storages[alias]
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 540, in _setup
    self._wrapped = storages[STATICFILES_STORAGE_ALIAS]
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\files\storage\handler.py", line 43, in __getitem__
    storage = self.create_storage(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\files\storage\handler.py", line 55, in create_storage
    return storage_cls(**options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\whitenoise\storage.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 463, in __init__
    self.hashed_files, self.manifest_hash = self.load_manifest()
                                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 473, in load_manifest
    content = self.read_manifest()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 467, in read_manifest
    with self.manifest_storage.open(self.manifest_name) as manifest:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\files\storage\base.py", line 22, in open
    return self._open(name, mode)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\core\files\storage\filesystem.py", line 68, in _open
    return File(open(self.path(name), mode))
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Dubba\OneDrive\Desktop\Fullstack\Module5_Django\venv\Lib\site-packages\django\contrib\staticfiles\storage.py", line 39, in path
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR 2024-06-23 16:31:44,278 basehttp "GET / HTTP/1.1" 500 187082
